### ISSUE TITLE
can't create train/test split

### ISSUE THREAD

**Issue by ekarais** [otto-de/recsys-dataset#1]
Hey, thanks for the great dataset!

When I run ```pipenv run python -m src.testset --train-set train.jsonl --days 2 --output-path 'out/' --seed 42 ``` as specified in the README, I get: ```ModuleNotFoundError: No module named 'pandas'```

Edit: I'm on python 3.10.6

**Comment by danielrolfes2307** [comment]
Hey @ekarais 
thanks for your feedback!
Could you try running `pipenv sync` before 
`pipenv run python -m src.testset --train-set train.jsonl --days 2 --output-path 'out/' --seed 42`?
This should install the needed dependencies in the virtual environment.

**Comment by ekarais** [comment]
Hi @danielrolfes2307 
Thanks for the tip, fixed it.
