### ISSUE TITLE
How is density calculated?

### ISSUE THREAD

**Issue by EmbraceLife** [otto-de/recsys-dataset#2]
Thank you so much for making this wonderful dataset and the README.md  itself is a beautiful resource to read.

I just wonder how is the `density` in [statistics](https://github.com/otto-de/recsys-dataset#dataset-statistics) session is calculated? What kind of info or implications does it provide? 

<img width="961" alt="Screen Shot 2022-11-14 at 07 56 58" src="https://user-images.githubusercontent.com/8749266/201551556-c31e26ae-a06c-40d8-943b-d2cc4062671f.png">

Thanks again!

**Comment by philippnormann** [comment]
Hey @EmbraceLife, thanks for your question and the positive feedback!

It refers to the density of the user-item matrix of our dataset. We calculated it by dividing the number of unique user-item interaction pairs by the total number of possible user-item pairs. In other words, the density represents the fraction of filled cells in the user-item matrix:

$$
density = \frac{| \\{\text{user-item interactions} \\}|}{|\text{users}| \times |\text{items}| }
$$

Large-scale recommender datasets like ours are often very sparse, which can challenge collaborative filtering approaches. We provided this information to help you select an appropriate algorithm that can handle this sparsity level.

I hope this answers your question :)

**Comment by EmbraceLife** [comment]
Thank you so much @philippnormann ! This is very helpful!
