### ISSUE TITLE
Question about items

### ISSUE THREAD

**Issue by ekarais** [otto-de/recsys-dataset#3]
Hi,

It seems that the only thing we know about an item is its `aid`. Is the `aid` totally random, or does it carry some information about the function of the item?

**Comment by philippnormann** [comment]
Hi @ekarais, thanks for your question! The `aids` are anonymized (different from article numbers in our shop)  and carry no information beyond uniquely identifying an item from the assortment. Given its already large size, we deliberately did not include content features to make the dataset more manageable and focus on collaborative filtering techniques that solve the multi-objective problem.

**Comment by ekarais** [comment]
Hi @philippnormann, thanks for the explanation.
