### ISSUE TITLE
beartype error

### ISSUE THREAD

**Issue by yxc8** [otto-de/recsys-dataset#4]
Hi,

I get the following error complaining about beartype import, when running `!pipenv run python3 -m src.testset --train-set train.jsonl --days 2 --output-path 'out/' --seed 42 `

Any suggestion on how to fix this?

Thanks!

> 
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/Users/yc/Desktop/kaggle/sample/recsys-dataset/src/testset.py", line 8, in <module>
>     from beartype import beartype
>   File "/Users/yc/.local/share/virtualenvs/recsys-dataset-XXnHBDKs/lib/python3.9/site-packages/beartype/__init__.py", line 57, in <module>
>     from beartype._decor.decormain import beartype
>   File "/Users/yc/.local/share/virtualenvs/recsys-dataset-XXnHBDKs/lib/python3.9/site-packages/beartype/_decor/decormain.py", line 24, in <module>
>     from beartype._data.datatyping import (
>   File "/Users/yc/.local/share/virtualenvs/recsys-dataset-XXnHBDKs/lib/python3.9/site-packages/beartype/_data/datatyping.py", line 129, in <module>
>     BeartypeReturn = Union[BeartypeableT, BeartypeConfedDecorator]
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 243, in inner
>     return func(*args, **kwds)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 316, in __getitem__
>     return self._getitem(self, parameters)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 421, in Union
>     parameters = _remove_dups_flatten(parameters)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
>     all_params = set(params)
> TypeError: unhashable type: 'list'

**Comment by yxc8** [comment]
Following up on this, it seems like using python3.10 instead of python3.9 avoids this problem. Not sure why the python3.9 won't work.

**Comment by philippnormann** [comment]
Hi [@yxc8](https://github.com/yxc8), thanks for your feedback! This issue is [a known CPython issue (#42965)](https://bugs.python.org/issue42965) resolved in 3.9.2. See [this beartype issue](https://github.com/beartype/beartype/issues/99) for more context. As you have already discovered, **the solution is to use a Python version >= 3.9.2.** I would like to integrate this minimum version requirement for our Python version into our Pipenv, but unfortunately, [this is currently not supported](https://github.com/pypa/pipenv/issues/1050).
